on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: publish package
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: .github/publi.sh "$(go list -m)" ${{ github.ref }}
